# Generated by Django 4.2.5 on 2023-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_deliverytime_order_preparationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='orderPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
