# Generated by Django 4.2.5 on 2023-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_totalamount_alter_orderfood_orderprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='isReady',
            field=models.BooleanField(default=False),
        ),
    ]
