# Generated by Django 4.2.5 on 2023-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderfood_isready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
